### ISSUE TITLE
Write method Student::compareTo(Student s)

### ISSUE THREAD

**Issue by ts12345** [InformatikMWG/ag-manager#15]
Damit die Liste mit Studenten ordentlich sortiert werden kann, muss die Methode compareTo des Interfaces Comparable<Student> überschrieben werden.

Sortierkriterien

1) classname
2) last name
3) first name

Rückgabewert

> 0, falls Objekt größer als Parameterobjekt s
= 0, falls Objekt gleich  Parameterobjekt s
< 0, falls Objekt kleiner  Parameterobjekt s

**Comment by Elduin** [comment]
Funktioniert!
