### ISSUE TITLE
Add Groups for each Jahrgangsstufe

### ISSUE THREAD

**Issue by ts12345** [InformatikMWG/ag-manager#43]
Eine SQL-Datei erstellen, mit der folgende Gruppen angelegt werden:

Id, Name
K05, 5. Jahrgangsstufe
K06, 6. Jahrgangsstufe
K07, 7. Jahrgangsstufe
K08, 8. Jahrgangsstufe
K09, 9. Jahrgangsstufe
K10, 10. Jahrgangstufe
Q11, Q11
Q12, Q12
Oberstufe, Oberstufe
Mittelstufe, Mittelstufe
Unterstufe, Unterstufe
CafeBlu, Café Blu

und die TestSuite so erweitern, dass bei resetDatabase() auch die Gruppen mit angelegt werden

**Comment by Elduin** [comment]
ich glaube fewrtig
