### ISSUE TITLE
Discussion: Treatment of additional articles in last names

### ISSUE THREAD

**Issue by SFr682k** [InformatikMWG/ag-manager#46]
Just noticed that my “Special Case” Mockup Data yielded an interesting credential combination

Names like “Rolf von der Kleingartenkolonie”, represented in the raw-Studends-CSV file as

    Rolf,von der Kleingartenkolonie,12Q

get user names like `Rv0815`. However, IMO `RK0815` would be more suitable.  
Should this be patched?

**Comment by ts12345** [comment]
Should be patched, if possible.
