### ISSUE TITLE
Enable using commas in input files: use tabstopp as CSV separator?

### ISSUE THREAD

**Issue by SFr682k** [InformatikMWG/ag-manager#49]
Currently the values inserted in a CSV file are separated by a comma.

This results in the comma character not being usable. However, we can’t forbid using commas, since they *will* be essential for the project descriptions and some project names (like »Nähen, Bügeln, Dosenbier: Haushaltstipps für Männer«).

I can imagine three possible solutions for fixing this deficiency:

1. **Change the separator.** This is the “easy way”, since “only” all `.split(",")`s in the code and commas inside the mockup data have to replaced. IMO, tabstopps (`\t`) would be a better separator.
2. **Make the comma usable.** One could imagine wrapping a value into `"`s, but implementing recognization of opening and closing `"`s would be a “larger business” (and require escaping every `"` used inside values).
3. **Escape every f****ing comma used inside values.** This solution is everything but comfortable for the poor sod preparing the input stuff and prone to failure.

I’d prefer solution 1 (and provide a simple Python script for replacing the separators inside the mockup data files).

**Comment by ts12345** [comment]
My vote is on solution 1)

I often use multiple hashtags ### as separators in my own projects ( s.split("###") works).

Replacing in the mockup data could be done inefficiently by "Search and Replace" :)

**Comment by SFr682k** [comment]
You’re right, coding a simple script gobbles up more time than “Search and replace” ;)

**Comment by ts12345** [comment]
On the other hand ... writing scripts helps tremendously in the long term ... at least the experience

**Comment by SFr682k** [comment]
**Separators exchanged to tabstopps** as far as I found the regarding lines in the Java code.  
Separators in the CSV files have been also exchanged.  

However, I didn’t regenerate the SQL data files in the Mockup Data Directory since I didn’t know whether this was necessary. You’re free to continue there.
